### ISSUE TITLE
Why did you multiply epsilon_k with gradient in the code?

### ISSUE THREAD

**Issue by jhss** [hmdolatabadi/AdvFlow#3]
Dear Author

I read your paper with great interest, but I have a question about the code.

According to the equation of the parameter mu in the page 6, mu is just subtracted from the gradient.
But in your code, you implemented the update rule as follows.

`mu    += (c.lr / (c.n_pop * c.sigma))*(torch.matmul(z_sample.view(c.n_pop, -1).t(), A.view(-1, 1))).view(1, -1)  # (lines 8 and 9 of Algorithm 1)`

The code said that the gradient is multiplied by the epsilon_k, and then update mu, which is different from the equation in the page 6. 

I saw that you implemented it following the Algorithm 1, but I want to know why you multiply the epsilon_k.

**Comment by hmdolatabadi** [comment]
Dear Ju,

Thanks for reaching out.
The key to your question is taking the gradient of the normal distribution log-likelihood.
After taking the gradient with respect to \mu, you can re-write the gradient in terms of \epsilon which is distributed according to a standard normal density. Then, if you put this gradient into the expectation of Eq. (6), you see that the multiplication of the loss L and \epsilon appears. I have attached my complete derivation below.

Meanwhile, if you have any further questions I would be more than happy to discuss.

Sincerely,
Hadi.

P.S. The confusion might be due to not dividing line 8 of Algorithm 1 by \sigma. You can assume that \sigma is hidden in \alpha since \sigma is a constant. I guess to avoid future confusions the gradient should be also divided by \sigma, as in the code. It would be fixed and put on arXiv after NeurIPS.

![Eq  6](https://user-images.githubusercontent.com/50772255/100525479-5794be80-3215-11eb-8e7a-dcfb4b75934f.png)

**Comment by jhss** [comment]
Thank you for the detailed answer!
I now make sense of the equation. It really helped me.
